// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("CSharp.UnionTypes.VSIX")]
[assembly: AssemblyProductAttribute("CSharp.UnionTypes")]
[assembly: AssemblyDescriptionAttribute("DSL, Parser & Code Generator for Discriminated Union Types (Sum Types) in C#")]
[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "CSharp.UnionTypes.VSIX";
        internal const System.String AssemblyProduct = "CSharp.UnionTypes";
        internal const System.String AssemblyDescription = "DSL, Parser & Code Generator for Discriminated Union Types (Sum Types) in C#";
        internal const System.String AssemblyVersion = "1.0.1";
        internal const System.String AssemblyFileVersion = "1.0.1";
    }
}
