// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("CSharp.AlgebraicTypes.VSIX")]
[assembly: AssemblyProductAttribute("CSharp.AlgebraicTypes")]
[assembly: AssemblyDescriptionAttribute("DSL, Parser & Code Generator for Algebraic Data Types (Sum & Product Types) in C#")]
[assembly: AssemblyVersionAttribute("1.0.1")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "CSharp.AlgebraicTypes.VSIX";
        internal const System.String AssemblyProduct = "CSharp.AlgebraicTypes";
        internal const System.String AssemblyDescription = "DSL, Parser & Code Generator for Algebraic Data Types (Sum & Product Types) in C#";
        internal const System.String AssemblyVersion = "1.0.1";
        internal const System.String AssemblyFileVersion = "1.0.1";
    }
}
