// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("CSharp.UnionTypes")>]
[<assembly: AssemblyProductAttribute("BrightSword.CSharpExtensions.DiscriminatedUnion")>]
[<assembly: AssemblyDescriptionAttribute("DSL, Parser & Code Generator for Discriminated Union Types (Sum Types) in C#")>]
[<assembly: AssemblyVersionAttribute("0.0.2")>]
[<assembly: InternalsVisibleToAttribute("BrightSword.CSharpExtensions.DiscriminatedUnion.Tests")>]
[<assembly: AssemblyFileVersionAttribute("0.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "CSharp.UnionTypes"
    let [<Literal>] AssemblyProduct = "BrightSword.CSharpExtensions.DiscriminatedUnion"
    let [<Literal>] AssemblyDescription = "DSL, Parser & Code Generator for Discriminated Union Types (Sum Types) in C#"
    let [<Literal>] AssemblyVersion = "0.0.2"
    let [<Literal>] InternalsVisibleTo = "BrightSword.CSharpExtensions.DiscriminatedUnion.Tests"
    let [<Literal>] AssemblyFileVersion = "0.0.2"
