// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("CSharp.AlgebraicTypes")>]
[<assembly: AssemblyProductAttribute("CSharp.AlgebraicTypes")>]
[<assembly: AssemblyDescriptionAttribute("DSL, Parser & Code Generator for Algebraic Data Types (Sum & Product Types) in C#")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "CSharp.AlgebraicTypes"
    let [<Literal>] AssemblyProduct = "CSharp.AlgebraicTypes"
    let [<Literal>] AssemblyDescription = "DSL, Parser & Code Generator for Algebraic Data Types (Sum & Product Types) in C#"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
