// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("BrightSword.CSharpExtensions.DiscriminatedUnion")>]
[<assembly: AssemblyProductAttribute("BrightSword.CSharpExtensions.DiscriminatedUnion")>]
[<assembly: AssemblyDescriptionAttribute("DSL, Parser & Code Generator for Discriminated Union Types (Sum Types) in C#")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: InternalsVisibleToAttribute("BrightSword.CSharpExtensions.DiscriminatedUnion.Tests")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "BrightSword.CSharpExtensions.DiscriminatedUnion"
    let [<Literal>] AssemblyProduct = "BrightSword.CSharpExtensions.DiscriminatedUnion"
    let [<Literal>] AssemblyDescription = "DSL, Parser & Code Generator for Discriminated Union Types (Sum Types) in C#"
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] InternalsVisibleTo = "BrightSword.CSharpExtensions.DiscriminatedUnion.Tests"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
